server:
  port: 8085
spring:
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://127.0.01:3306/world?useUnicode=true&characterEncoding=utf8&userSSL=false&serverTimezone=GMT%2B8
#    username: root
#    password: 123456
#    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.240:8066/wlos_db?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false
    username: wlosdb
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
DbType: mysql